name: dexter_health
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.1.4
  google_sign_in: ^5.1.0
  provider: ^6.0.4
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  cloud_firestore: ^3.5.1
  intl: ^0.17.0
  desktop_webview_auth: ^0.0.9
  
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  assets_scanner: ^2.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
